export const apartmentData = {
  title: "Modern Apartment in City Center",
  images: [
    "/assets/apartment-city-center.jpg",
    "/assets/apartment-city-center-2.jpg",
    "/assets/apartment-city-center-3.jpg",
  ],
  description: "A stylish and modern apartment located in the heart of the city.",
  longDescription: "This is a detailed description of the apartment, highlighting all its features, benefits, and any other important information.",
  price: "250",
  rating: 4.8,
  reviews: 172,
  features: ["Wifi", "Air conditioning", "Kitchen", "Free parking"],
  amenities: [
    "Wifi",
    "Air conditioning",
    "Kitchen",
    "Free parking",
    "Washer",
    "Dryer",
    "Heating",
    "TV",
    "Private entrance",
    "Laptop-friendly workspace",
    "Iron",
    "Hair dryer",
    "First aid kit",
    "Fire extinguisher",
    "Carbon monoxide detector",
    "Smoke detector",
  ],
  host: {
    name: "John Doe",
    since: "Host since 2015",
  },
  location: {
    lat: 48.8566,
    lng: 2.3522,
    address: "Hotel de ville, Paris",
  },
};
